version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=postgresql://mediafind:${DB_PASSWORD}@db:5432/mediafind
      - DJANGO_SUPERUSER_USERNAME=${ADMIN_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${ADMIN_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
      - POPULATE_DB=false
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - mediafind-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediafind
      - POSTGRES_USER=mediafind
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    networks:
      - mediafind-network

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - mediafind-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl/certs
      - static_data:/var/www/static
      - media_data:/var/www/media
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - mediafind-network

volumes:
  postgres_data:
  media_data:
  static_data:

networks:
  mediafind-network:
    driver: bridge
