services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://mediafind:mediafind123@db:5432/mediafind
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mediafind.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - POPULATE_DB=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mediafind-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediafind
      - POSTGRES_USER=mediafind
      - POSTGRES_PASSWORD=mediafind123
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256 --auth-local=scram-sha-256
    ports:
      - "5432:5432"
    networks:
      - mediafind-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediafind -d mediafind"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - mediafind-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mediafind-network:
    driver: bridge
