services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://mediafind:mediafind123@db:5432/mediafind
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@mediafind.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - POPULATE_DB=true
    depends_on:
      - db
    networks:
      - mediafind-network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mediafind
      - POSTGRES_USER=mediafind
      - POSTGRES_PASSWORD=mediafind123
    ports:
      - "5432:5432"
    networks:
      - mediafind-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - mediafind-network

volumes:
  postgres_data:

networks:
  mediafind-network:
    driver: bridge
